/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { Addressable } from "ethers";
import { Contract, ContractFactory, ContractTransactionResponse, Interface } from "ethers"
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers"
import type { NonPayableOverrides } from "../common.js"
  import type { MyContract2, MyContract2Interface } from "../MyContract2.js";

  const _abi = [
  {
    "inputs": [],
    "stateMutability": "nonpayable",
    "type": "constructor"
  }
] as const;

  const _bytecode = "0x6080604052348015600e575f80fd5b50603e80601a5f395ff3fe60806040525f80fdfea2646970667358221220191900adfc5955229c472a1d34ba20d68eac3a0e5ce596890f6c918db250368d64736f6c63430008180033";

  
      type MyContract2ConstructorParams = [signer?: Signer] | ConstructorParameters<typeof ContractFactory>;

      const isSuperArgs = (xs: MyContract2ConstructorParams): xs is ConstructorParameters<typeof ContractFactory> =>
        xs.length > 1
    

  export class MyContract2__factory extends ContractFactory {
    
      constructor(...args: MyContract2ConstructorParams) {
        if (isSuperArgs(args)) {
          super(...args);
        } else {
          super(_abi, _bytecode, args[0]);
        }
        
      }
    
    override getDeployTransaction(overrides?: NonPayableOverrides & { from?: string }): Promise<ContractDeployTransaction> {
      return super.getDeployTransaction(overrides || {});
    };
    override deploy(overrides?: NonPayableOverrides & { from?: string }) {
      return super.deploy(overrides || {}) as Promise<MyContract2 & {
        deploymentTransaction(): ContractTransactionResponse;
      }>;
    }
    override connect(runner: ContractRunner | null): MyContract2__factory {
      return super.connect(runner) as MyContract2__factory;
    }
    
    
    static readonly bytecode = _bytecode;
    static readonly abi = _abi;
    static createInterface(): MyContract2Interface {
      return new Interface(_abi) as MyContract2Interface;
    }
    
    override attach(address: string | Addressable): MyContract2 {
      return super.attach(address) as MyContract2;
    }
  static connect(address: string, runner?: ContractRunner | null): MyContract2 {
      return new Contract(address, _abi, runner) as unknown as MyContract2;
    }
  }

  
  