/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { Addressable } from "ethers";
import { Contract, ContractFactory, ContractTransactionResponse, Interface } from "ethers"
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers"
import type { NonPayableOverrides } from "../common.js"
  import type { MyContract3, MyContract3Interface } from "../MyContract3.js";

  const _abi = [
  {
    "inputs": [],
    "stateMutability": "nonpayable",
    "type": "constructor"
  }
] as const;

  const _bytecode = "0x6080604052348015600e575f80fd5b50603e80601a5f395ff3fe60806040525f80fdfea2646970667358221220e196ca8c6beb422a6ec5a19f4d88c055988a6ffd97ad3e8ab3828b879917ffff64736f6c63430008180033";

  
      type MyContract3ConstructorParams = [signer?: Signer] | ConstructorParameters<typeof ContractFactory>;

      const isSuperArgs = (xs: MyContract3ConstructorParams): xs is ConstructorParameters<typeof ContractFactory> =>
        xs.length > 1
    

  export class MyContract3__factory extends ContractFactory {
    
      constructor(...args: MyContract3ConstructorParams) {
        if (isSuperArgs(args)) {
          super(...args);
        } else {
          super(_abi, _bytecode, args[0]);
        }
        
      }
    
    override getDeployTransaction(overrides?: NonPayableOverrides & { from?: string }): Promise<ContractDeployTransaction> {
      return super.getDeployTransaction(overrides || {});
    };
    override deploy(overrides?: NonPayableOverrides & { from?: string }) {
      return super.deploy(overrides || {}) as Promise<MyContract3 & {
        deploymentTransaction(): ContractTransactionResponse;
      }>;
    }
    override connect(runner: ContractRunner | null): MyContract3__factory {
      return super.connect(runner) as MyContract3__factory;
    }
    
    
    static readonly bytecode = _bytecode;
    static readonly abi = _abi;
    static createInterface(): MyContract3Interface {
      return new Interface(_abi) as MyContract3Interface;
    }
    
    override attach(address: string | Addressable): MyContract3 {
      return super.attach(address) as MyContract3;
    }
  static connect(address: string, runner?: ContractRunner | null): MyContract3 {
      return new Contract(address, _abi, runner) as unknown as MyContract3;
    }
  }

  
  