/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { Addressable } from "ethers";
import { Contract, ContractFactory, ContractTransactionResponse, Interface } from "ethers"
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers"
import type { NonPayableOverrides } from "../common.js"
  import type { MyContract, MyContractInterface } from "../MyContract.js";

  const _abi = [
  {
    "inputs": [],
    "stateMutability": "nonpayable",
    "type": "constructor"
  }
] as const;

  const _bytecode = "0x6080604052348015600e575f80fd5b50603e80601a5f395ff3fe60806040525f80fdfea26469706673582212209576d46be97d6efc4d07dbd66ce6199f72e65a68a8c70a335a748f816dc636c964736f6c63430008180033";

  
      type MyContractConstructorParams = [signer?: Signer] | ConstructorParameters<typeof ContractFactory>;

      const isSuperArgs = (xs: MyContractConstructorParams): xs is ConstructorParameters<typeof ContractFactory> =>
        xs.length > 1
    

  export class MyContract__factory extends ContractFactory {
    
      constructor(...args: MyContractConstructorParams) {
        if (isSuperArgs(args)) {
          super(...args);
        } else {
          super(_abi, _bytecode, args[0]);
        }
        
      }
    
    override getDeployTransaction(overrides?: NonPayableOverrides & { from?: string }): Promise<ContractDeployTransaction> {
      return super.getDeployTransaction(overrides || {});
    };
    override deploy(overrides?: NonPayableOverrides & { from?: string }) {
      return super.deploy(overrides || {}) as Promise<MyContract & {
        deploymentTransaction(): ContractTransactionResponse;
      }>;
    }
    override connect(runner: ContractRunner | null): MyContract__factory {
      return super.connect(runner) as MyContract__factory;
    }
    
    
    static readonly bytecode = _bytecode;
    static readonly abi = _abi;
    static createInterface(): MyContractInterface {
      return new Interface(_abi) as MyContractInterface;
    }
    
    override attach(address: string | Addressable): MyContract {
      return super.attach(address) as MyContract;
    }
  static connect(address: string, runner?: ContractRunner | null): MyContract {
      return new Contract(address, _abi, runner) as unknown as MyContract;
    }
  }

  
  