/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */


import { ethers } from 'ethers'
import { DeployContractOptions, FactoryOptions, HardhatEthersHelpers as HardhatEthersHelpersBase} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from "./index.js";

declare module "@nomicfoundation/hardhat-ethers/types" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
  getContractFactory(name: 'Lock', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.Lock__factory>
getContractFactory(name: 'MyContract', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.MyContract__factory>
getContractFactory(name: 'MyContract2', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.MyContract2__factory>
getContractFactory(name: 'MyContract3', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.MyContract3__factory>

  getContractAt(name: 'Lock', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.Lock>
getContractAt(name: 'MyContract', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.MyContract>
getContractAt(name: 'MyContract2', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.MyContract2>
getContractAt(name: 'MyContract3', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.MyContract3>

  deployContract(name: 'Lock', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Lock>
deployContract(name: 'MyContract', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MyContract>
deployContract(name: 'MyContract2', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MyContract2>
deployContract(name: 'MyContract3', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MyContract3>

  deployContract(name: 'Lock', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Lock>
deployContract(name: 'MyContract', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MyContract>
deployContract(name: 'MyContract2', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MyContract2>
deployContract(name: 'MyContract3', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MyContract3>

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
  